version: '3.8'
services:
  postgres:
    image: postgres:17-alpine
    container_name: taxi_postgres_q1
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ny_taxi
    ports:
      - "5434:5432"  # Port différent
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]

  kestra:
    image: kestra/kestra:latest
    container_name: kestra_q1
    command: server standalone
    ports:
      - "8082:8080"  # Port différent
    environment:
      KESTRA_LOG_LEVEL: INFO
    volumes:
      - ./flows:/app/flows
      - ./data:/app/data
    depends_on:
      - postgres
